{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quake-watch-app-chart.serviceAccountName" . }}
  labels:
    {{- include "quake-watch-app-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  - name: ghcr-image-pull-secret # The name of the existing secret
{{- end }}