name: Publish and deploy the Python App & Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  lint:
    uses: ./.github/workflows/reusable-python-task.yaml
    with:
      job-name: Lint
      python-version: ${{ matrix.python-version }}
      requirements-path: ./requirements.txt
      task-script: |
        eval "$(pyenv init --path)"
        
        echo "Running Lint with Python ${{ matrix.python-version }}..."

        # Add the 'app' directory itself to the PYTHONPATH.
        # Allow 'app.py' to find 'dashboard.py' and 'utils.py' directly
        export PYTHONPATH=$PYTHONPATH:./app

        # Explicitly lint 'app/app.py' now that the PYTHONPATH is set correctly.
        pylint app/app.py --fail-under=7.0

        echo "Lint completed."
      job-timeout-minutes: 15
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
  # test:
  #   uses: ./.github/workflows/reusable-python-job.yaml
  #   with:
  #     job-name: Test
  #     python-version: ${{ matrix.python-version }}
  #     requirements-path: app/requirements.txt
  #     task-script: |
  #       pytest app/tests # Adjust to the correct path for tests
  #     job-timeout-minutes: 15
  #   strategy:
  #     matrix:
  #       python-version: [ "3.12", "3.13" ]

  build-and-publish:
    runs-on: self-hosted
    needs: lint
    # needs: [lint, test] # Uncomment to reactivate both lint and test

    permissions:
      contents: read
      packages: write # Crucial for pushing Docker images and Helm charts to GHCR

    outputs:
      chart_name: ${{ steps.extract_metadata_action.outputs.name }} # Access output from the custom action
      # This is now correctly reflecting the Docker image tag (which is appVersion)
      image_tag: ${{ steps.extract_metadata_action.outputs.app_version }}
      base_chart_version: ${{ steps.extract_metadata_action.outputs.base_version }} # This is the Helm chart's own version
      argocd_app_name: ${{ steps.extract_metadata_action.outputs.app_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract Chart Metadata
        id: extract_metadata_action # Assign an ID to the custom action step
        uses: ./.github/actions/extract-chart-metadata
        with:
          chart-path: './k8s' # Pass the base path to your chart directory

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5 # Using the recommended action
        with:
          context: .
          push: true
          # Use the dynamic app_version from Chart.yaml for the Docker image tag
          tags: ghcr.io/${{ github.repository_owner }}/quake-watch-app:${{ steps.extract_metadata_action.outputs.app_version }}
          load: false
          no-cache: false
          pull: false

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.0

      - name: Package & Push Helm Chart to GHCR OCI
        run: |
          CHART_DIR="./k8s/${{ steps.extract_metadata_action.outputs.chart_directory }}"
          CHART_NAME="${{ steps.extract_metadata_action.outputs.name }}"
          CHART_VERSION="${{ steps.extract_metadata_action.outputs.base_version }}"

          EXPECTED_CHART_PACKAGE_FILENAME="${CHART_NAME}-${CHART_VERSION}.tgz"

          echo "Packaging Helm chart from: $CHART_DIR"
          echo "Expected packaged filename: $EXPECTED_CHART_PACKAGE_FILENAME"

          helm package "$CHART_DIR" --destination .

          if [ ! -f "$EXPECTED_CHART_PACKAGE_FILENAME" ]; then
            echo "Error: Helm package '$EXPECTED_CHART_PACKAGE_FILENAME' not found after packaging."
            exit 1
          fi

          GHCR_OCI_TARGET="oci://ghcr.io/${{ github.repository_owner }}"
          echo "Pushing Helm chart '$EXPECTED_CHART_PACKAGE_FILENAME' to GHCR OCI Repository: $GHCR_OCI_TARGET"
          helm push "$EXPECTED_CHART_PACKAGE_FILENAME" "$GHCR_OCI_TARGET" --debug
        shell: bash

  deploy:
    runs-on: self-hosted
    needs: build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Kubeconfig for K3D Cluster
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
#          chmod 600 ~/.kube/config
#          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Set up Kubeconfig for K3D Cluster
        uses: ./.github/actions/setup-kubeconfig
        with:
          kubeconfig-secret: ${{ secrets.KUBECONFIG }}

      - name: Get ArgoCD Admin Password
        id: get_argocd_password
        run: |
          ARGO_CD_INITIAL_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "Retrieved ArgoCD Admin Password."
          echo "argocd_password=$ARGO_CD_INITIAL_PASSWORD" >> "$GITHUB_OUTPUT"

      - name: Log in to ArgoCD
        run: |
          argocd login ${{ secrets.ARGO_CD_SERVER }} \
            --username admin \
            --password ${{ steps.get_argocd_password.outputs.argocd_password }} \
            --insecure

      - name: Update ArgoCD Application with Chart.yaml Version and Sync
        run: |
          APP_NAME="${{ needs.build-and-publish.outputs.argocd_app_name }}"

          # CORRECTED: Use base_chart_version for ArgoCD's targetRevision for the OCI chart
          CHART_VERSION_FOR_ARGOCD="${{ needs.build-and-publish.outputs.base_chart_version }}"

          echo "Updating ArgoCD application '${APP_NAME}' targetRevision to Helm chart version: ${CHART_VERSION_FOR_ARGOCD}"
          kubectl patch application "${APP_NAME}" -n argocd --type='json' -p='[{"op": "replace", "path": "/spec/source/targetRevision", "value":"'"$CHART_VERSION_FOR_ARGOCD"'"}]'

          echo "Triggering sync for ArgoCD application: ${APP_NAME}"
          argocd app sync "$APP_NAME" --prune

          argocd app wait "$APP_NAME" --health --sync --timeout 300

  call-e2e-test:
    needs: [deploy, build-and-publish]
    uses: ./.github/workflows/test-app-with-n8n.yaml # Using n8n self-hosted agent
    with:
      build-image-tag: ${{ needs.build-and-publish.outputs.image_tag }}
      app-name-for-port-forward: ${{ needs.build-and-publish.outputs.argocd_app_name }}
      app-internal-port: 5000
      app-local-port: 8000
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }} # Pass secrets directly. They are not visible in workflow logs.
      N8N_WEBHOOK_URL: ${{ secrets.N8N_TEST_WEBHOOK_URL }} # Use the existing secret name
